<a href="https://colab.research.google.com/github/yusef-atef/Ai_course/blob/main/Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [4]:
import numpy as np


#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [5]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [6]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [7]:
my_array = np.array([1, 2, 3, 4, 5, 6])
item_size = my_array.itemsize
array_size = my_array.size
memory_size = item_size * array_size
print(f"Memory size of the array: {memory_size} bytes")

Memory size of the array: 48 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [8]:
print(np.info)

<function info at 0x7e666e1937e0>


#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [9]:
null_vector = np.zeros(12)
null_vector[5] = 1

#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [10]:
vector = np.arange(20, 60)

#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [11]:
vector = vector[::-1]

#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [12]:
one_d_array = np.arange(12, 21)
matrix_3x3 = one_d_array.reshape(3, 3)

#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [13]:
my_array = np.array([3, 7, 0, 0, 9, 0])
indices = np.nonzero(my_array)

#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [14]:
identity_matrix = np.eye(4)

#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [15]:
random_array = np.random.rand(2, 2, 2)

#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [16]:
random_array = np.random.rand(9, 9)
min_value = random_array.min()
max_value = random_array.max()

#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [17]:
random_vector = np.random.rand(20)
mean_value = random_vector.mean()

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [18]:
size = 5
array_with_border = np.ones((size, size), dtype=int)
array_with_border[1:size-1, 1:size-1] = 0

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [19]:
my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
padded_array = np.pad(my_array, pad_width=1, mode='constant', constant_values=0)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [20]:
print(f"1. 0 * np.nan = {0 * np.nan}")
print(f"2. np.nan == np.nan = {np.nan == np.nan}")
print(f"3. np.inf > np.nan = {np.inf > np.nan}")
print(f"4. np.nan - np.nan = {np.nan - np.nan}")
print(f"5. np.nan in set([np.nan]) = {np.nan in set([np.nan])}")
print(f"6. 0.7 == 7 * 0.1 = {0.7 == 7 * 0.1}")

1. 0 * np.nan = nan
2. np.nan == np.nan = False
3. np.inf > np.nan = False
4. np.nan - np.nan = nan
5. np.nan in set([np.nan]) = True
6. 0.7 == 7 * 0.1 = False


#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [22]:
matrix = np.zeros((6, 6), dtype=int)
values = [1, 2, 3, 4]
for i in range(len(values)):
    matrix[i + 1, i] = values[i]
print(matrix)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 0 0]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [23]:
size = 6
checkerboard = np.zeros((size, size), dtype=int)
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [24]:
array_shape = (8, 9, 10)
linear_index = 99
index_coords = np.unravel_index(linear_index, array_shape)
print(f"The index (x, y, z) of the 100th element is: {index_coords}")

The index (x, y, z) of the 100th element is: (np.int64(1), np.int64(0), np.int64(9))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [25]:
pattern = np.array([[0, 1],
                    [1, 0]])
checkerboard_matrix = np.tile(pattern, (4, 4))
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [26]:
random_matrix = np.random.rand(6, 6)
min_val = random_matrix.min()
max_val = random_matrix.max()
normalized_matrix = (random_matrix - min_val) / (max_val - min_val)
print("Original 6x6 Random Matrix:")
print(random_matrix)
print("\nNormalized 6x6 Matrix:")
print(normalized_matrix)

Original 6x6 Random Matrix:
[[0.83010483 0.32825324 0.95544693 0.41212772 0.53844506 0.19715046]
 [0.58556944 0.41528773 0.43203717 0.63968362 0.64379774 0.77213746]
 [0.22759508 0.47369003 0.55004332 0.35026256 0.51118195 0.06288584]
 [0.8957674  0.42586732 0.47528475 0.51505354 0.01774132 0.76283218]
 [0.70594277 0.61752408 0.07459827 0.83003018 0.31993983 0.45771523]
 [0.80506096 0.72798516 0.78484379 0.07458749 0.39072239 0.33974574]]

Normalized 6x6 Matrix:
[[0.86633108 0.33114009 1.         0.42058658 0.55529554 0.19132778]
 [0.60555052 0.42395652 0.44181868 0.66325965 0.66764708 0.80451277]
 [0.22379492 0.48623865 0.5676643  0.35461155 0.52622126 0.0481436 ]
 [0.93635579 0.43523894 0.48793931 0.53035005 0.         0.79458931]
 [0.73392058 0.63962799 0.06063411 0.86625147 0.3222744  0.4692026 ]
 [0.83962347 0.75742731 0.81806322 0.06062262 0.39775924 0.34339607]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [27]:
random_matrix = np.random.rand(6, 6)
min_val = random_matrix.min()
max_val = random_matrix.max()
normalized_matrix = (random_matrix - min_val) / (max_val - min_val)
print("Original 6x6 Random Matrix:")
print(random_matrix)
print("\nNormalized 6x6 Matrix:")
print(normalized_matrix)
number_of_elements = random_matrix.size
item_size_bytes = random_matrix.itemsize
total_bytes = random_matrix.nbytes
print("\n--- Array Size Information ---")
print(f"Number of elements: {number_of_elements}")
print(f"Length of one array element in bytes: {item_size_bytes}")
print(f"Total bytes consumed by the elements: {total_bytes}")

Original 6x6 Random Matrix:
[[0.38398912 0.72518533 0.52046575 0.55689283 0.11562846 0.37839665]
 [0.83013551 0.92050566 0.29726681 0.60665292 0.3105512  0.45284447]
 [0.86230115 0.6093949  0.8224462  0.82936312 0.9800248  0.18849233]
 [0.30051158 0.96925791 0.43013112 0.37438469 0.74258593 0.67666133]
 [0.37109612 0.43020475 0.94265288 0.94089744 0.72649277 0.21503041]
 [0.0659163  0.20606807 0.28426184 0.99006533 0.04747538 0.20942362]]

Normalized 6x6 Matrix:
[[0.35700969 0.71898703 0.50179865 0.54044439 0.07230406 0.3510766 ]
 [0.83032938 0.92620368 0.26500541 0.5932352  0.2790989  0.43005878]
 [0.86445412 0.59614418 0.82217175 0.82950994 0.98934793 0.14960583]
 [0.2684478  0.97792527 0.40596204 0.34682028 0.73744744 0.6675076 ]
 [0.34333142 0.40604016 0.94969981 0.94783746 0.7203741  0.17776025]
 [0.01956409 0.16825205 0.25120834 1.         0.         0.17181198]]

--- Array Size Information ---
Number of elements: 36
Length of one array element in bytes: 8
Total bytes consumed by

#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [29]:
matrix_a = np.random.rand(6, 3)
matrix_b = np.random.rand(3, 4)
result_matrix = matrix_a @ matrix_b
print("Matrix A (6x3):")
print(matrix_a)
print("\nMatrix B (3x4):")
print(matrix_b)
print("\nResult of A @ B (6x4):")
print(result_matrix)

Matrix A (6x3):
[[0.81044694 0.48927762 0.35794868]
 [0.90471515 0.10324681 0.9225678 ]
 [0.18646748 0.4937548  0.67950482]
 [0.76696406 0.74777875 0.03478331]
 [0.12702886 0.79356885 0.99966985]
 [0.47865621 0.05665043 0.39509802]]

Matrix B (3x4):
[[0.84162917 0.41569484 0.85836654 0.56338892]
 [0.05755479 0.95287038 0.64706084 0.84669677]
 [0.19415699 0.29008409 0.8289524  0.31554071]]

Result of A @ B (6x4):
[[0.77975429 0.90695198 1.30897534 0.98381398]
 [0.94649999 0.74208849 1.60814897 0.88823293]
 [0.31728503 0.74511143 1.04282399 0.73752574]
 [0.69529099 1.0414493  1.17102833 1.07621645]
 [0.34667777 1.09896181 1.45120337 1.05891537]
 [0.48282257 0.36756708 0.7750362  0.44230485]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [30]:
Z = np.arange(10)
print("Original array:")
print(Z)
Z[(Z > 3) & (Z < 8)] *= -1
print("\nArray after negating elements between 3 and 8:")
print(Z)

Original array:
[0 1 2 3 4 5 6 7 8 9]

Array after negating elements between 3 and 8:
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
print(f"Result from Python's sum(): {sum(range(5), -1)}")
from numpy import *
print(f"Result from NumPy's sum(): {sum(range(5), -1)}")

Result from Python's sum(): 9
Result from NumPy's sum(): 10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [32]:
import numpy as np
array_a = np.array([1, 2])
array_b = np.array([4, 5])
print(array_a > array_b)
print(array_a >= array_b)
print(array_a < array_b)
print(array_a <= array_b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [33]:
print(f"np.array(0) / np.array(0) = {np.array(0) / np.array(0)}")
print(f"np.array(0) // np.array(0) = {np.array(0) // np.array(0)}")
print(f"np.array([np.nan]).astype(int).astype(float) = {np.array([np.nan]).astype(int).astype(float)}")
a = np.arange(3)
print(f"\nConsidering integer vector a: {a}")
print(f"a ** a = {a ** a}")
print(f"a << a >> 2 = {a << a >> 2}")
print(f"a < -a = {a < -a}")
print(f"1j * a = {1j * a}")
print(f"a / 1 / 1 = {a / 1 / 1}")
try:
    print("a <a> a = ", a<a>a)
except SyntaxError as e:
    print(f"a <a> a = SyntaxError: {e}")

np.array(0) / np.array(0) = nan
np.array(0) // np.array(0) = 0
np.array([np.nan]).astype(int).astype(float) = [-9.22337204e+18]

Considering integer vector a: [0 1 2]
a ** a = [1 1 4]
a << a >> 2 = [0 0 2]
a < -a = [False False False]
1j * a = [0.+0.j 0.+1.j 0.+2.j]
a / 1 / 1 = [0. 1. 2.]


/tmp/ipython-input-27513209.py:1: RuntimeWarning: invalid value encountered in divide
  print(f"np.array(0) / np.array(0) = {np.array(0) / np.array(0)}")
/tmp/ipython-input-27513209.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(f"np.array(0) // np.array(0) = {np.array(0) // np.array(0)}")
/tmp/ipython-input-27513209.py:3: RuntimeWarning: invalid value encountered in cast
  print(f"np.array([np.nan]).astype(int).astype(float) = {np.array([np.nan]).astype(int).astype(float)}")


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [ ]:
Z = np.random.uniform(low=-5.0, high=5.0, size=10)
print("Original float array:")
print(Z)
rounded_Z = np.copysign(np.ceil(np.abs(Z)), Z)
print("\nRounded away from zero:")
print(rounded_Z)

#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [ ]:
import numpy as np
array1 = np.array([1, 5, 2, 7, 3])
array2 = np.array([4, 2, 6, 1, 8])
common_values = np.intersect1d(array1, array2)
print("Array 1:", array1)
print("Array 2:", array2)
print("Common values:", common_values)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`